[package]
name = "day05-alt"
version = "0.1.0"
authors = ["Dmitri S. <dmitris@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
